import json
from typing import List

import httpx

from app.core.config import settings
from app.schemas.loan_schemas import LoanReviewRequest


async def generate_reviewer_answer(
    request: LoanReviewRequest,
    missing_documents: List[str],
    risk_flags: List[str],
) -> str:
    """Generate the final reviewer-facing answer.

    MVP strategy:
    - Start with mock provider so demo never breaks.
    - Switch `LLM_PROVIDER=ollama` only after backend + UI work.
    - Keep prompt strict: the model must assist the reviewer, not approve/reject.
    """

    provider = settings.llm_provider.lower().strip()
    prompt = _build_prompt(request, missing_documents, risk_flags)

    if provider == "ollama":
        return await _call_ollama(prompt)

    # Safe fallback for capstone demo.
    return _mock_answer(request, missing_documents, risk_flags)


def _build_prompt(request: LoanReviewRequest, missing_documents: List[str], risk_flags: List[str]) -> str:
    return f"""
You are LoanFlow AI, an assistant for a human loan reviewer.

Rules:
- Do not approve a loan.
- Do not reject a loan.
- Always recommend human review for final decision.
- Be concise and practical.

Loan context:
- Loan ID: {request.loan_id}
- Borrower: {request.borrower_name}
- Amount: {request.loan_amount}
- Annual income: {request.annual_income}
- Credit score: {request.credit_score}
- Reviewer question: {request.question}

Detected missing documents: {missing_documents}
Detected risk flags: {risk_flags}

Return a reviewer-facing response with next steps.
""".strip()


async def _call_ollama(prompt: str) -> str:
    """Call local Ollama API.

    Ollama runs locally on http://localhost:11434 by default. The API can be used
    without auth for local development. If this fails, raise a clear error so the UI
    can show something helpful.
    """

    url = f"{settings.ollama_base_url.rstrip('/')}/api/generate"
    payload = {
        "model": settings.ollama_model,
        "prompt": prompt,
        "stream": False,
        "options": {"temperature": 0.2},
    }
    async with httpx.AsyncClient(timeout=60) as client:
        response = await client.post(url, json=payload)
        response.raise_for_status()
        data = response.json()
    return data.get("response", "No response generated by Ollama.").strip()


def _mock_answer(request: LoanReviewRequest, missing_documents: List[str], risk_flags: List[str]) -> str:
    """Deterministic response used for first working demo and fallback."""

    parts = [
        f"Loan {request.loan_id} for {request.borrower_name} should be routed to a human reviewer.",
    ]
    if missing_documents:
        parts.append(f"Missing documents to request: {', '.join(missing_documents)}.")
    if risk_flags:
        parts.append(f"Risk flags to verify: {', '.join(risk_flags)}.")
    if not missing_documents and not risk_flags:
        parts.append("No major MVP risk flags were detected, but final decision still requires human review.")
    parts.append("LoanFlow AI does not approve or reject loans.")
    return " ".join(parts)
